# Generated by Django 3.1.4 on 2022-05-22 11:22

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Product Id')),
                ('scrape_url', models.CharField(max_length=250, verbose_name='Scrape url')),
                ('original_size', models.CharField(max_length=100, verbose_name='Original size')),
                ('alt_data', models.CharField(max_length=100, verbose_name='Alt data')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Image',
                'db_table': 'product_image',
            },
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['updated_at'], name='product_image_updated_at_bri'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='product_image_created_at_bri'),
        ),
    ]
