# Generated by Django 3.1.4 on 2022-05-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='scrape_url',
            field=models.CharField(max_length=250, unique=True, verbose_name='Scrape url'),
        ),
    ]
